using './main.bicep'

param location = 'swedencentral'
param migrateProjectBaseName = 'az-migrate-workshop'
// timestamp parameter will be auto-generated by Bicep for uniqueness
param vnetAddressPrefix = '10.1.0.0/16'
param subnetAddressPrefix = '10.1.0.0/24'
